### ISSUE TITLE
Plugin mpd does not support over socket connection?

### ISSUE THREAD

**Issue by seamus-45** [shdown/luastatus#12]
Is there any chance to implement this?

**Comment by shdown** [comment]
Done. Unfortunately, `libmpdclient2` isn’t thread-safe (calls `getenv`), so we can’t use it.

**Comment by seamus-45** [comment]
It's work. 
Unfortunately, the status update does not occur immediately, if the music is already playing, then the update occurs only with the next track, or after user interaction with mpd.

**Comment by shdown** [comment]
Works for me. Please do update and provide some info, including what `cb` is called with:
```lua
function printtable(t, align)
    align = align or ''
    for k, v in pairs(t) do
        if type(v) == 'table' then
            print(align .. k .. ':')
            printtable(v, align .. '\t')
        else
            print(align .. k .. ' => ' .. v)
        end
    end
end
…
    cb = function(t)
        print('--- cb called ---')
        printtable(t)
        io.stdout:flush()
        …
    end,
…
```

**Comment by seamus-45** [comment]
Hmm, strange. It works perfectly when launched like this:
```
$ luastatus -b lemonbar 3<&0 0</dev/null -B in_fd=3 4>&1 1>&2 -B out_fd=4 mpd.lua
Dreaming Cooper - Cosmic Serenity
```
But not in case if pipe to lemonbar added.

**Comment by shdown** [comment]
There’s a bug in lemonbar.
![2017-02-06-115152_604x111_scrot](https://cloud.githubusercontent.com/assets/5462697/22640218/1e140326-ec6b-11e6-8d50-761e14136406.png)

**Comment by seamus-45** [comment]
sadly, looks like lemonbar reads only first line. above example works perfect like this:
`{ echo -n a; echo b } | lemonbar -p`

**Comment by seamus-45** [comment]
why outputs so differ?
`$ luastatus -b lemonbar 3<&0 0</dev/null -B in_fd=3 4>&1 1>&2 -B out_fd=4 mpd.lua | hexdump`
```
Royal Philharmonic Orchestra - When the Tigers Broke Free / Eclipse
0000000 520a 796f 6c61 5020 6968 686c 7261 6f6d
0000010 696e 2063 724f 6863 7365 7274 2061 202d
0000020 6857 6e65 7420 6568 5420 6769 7265 2073
0000030 7242 6b6f 2065 7246 6565 2f20 4520 6c63
0000040 7069 6573 520a 796f 6c61 5020 6968 686c
0000050 7261 6f6d 696e 2063 724f 6863 7365 7274
0000060 2061 202d 6857 6e65 7420 6568 5420 6769
0000070 7265 2073 7242 6b6f 2065 7246 6565 2f20
```
`$ echo 'Royal Philharmonic Orchestra - When the Tigers Broke Free / Eclipse' | hexdump`
```
0000000 6f52 6179 206c 6850 6c69 6168 6d72 6e6f
0000010 6369 4f20 6372 6568 7473 6172 2d20 5720
0000020 6568 206e 6874 2065 6954 6567 7372 4220
0000030 6f72 656b 4620 6572 2065 202f 6345 696c
0000040 7370 0a65
0000044
```

and why `\x0a` byte near beginning?

**Comment by shdown** [comment]
> why outputs so differ?

> and why \x0a byte near beginning?

Because luastatus outputs multiple lines; first of them is empty. This is OK. Again: there’s a bug in lemonbar, it uses `poll` and `fgets`, which calls `read`, which, in our case, reads multiple lines at once. Please report a bug to lemonbar.

**Comment by shdown** [comment]
OK, I opened a pull request. Please try lemonbar from https://github.com/shdown/bar/tree/buffer-bug-fix.

**Comment by seamus-45** [comment]
This work like a charm. Thank you. :+1:
