### ISSUE TITLE
ошибка в виджете mem-free.lua

### ISSUE THREAD

**Issue by itspec-ru** [shdown/luastatus#15]
Виджет contrib/widget-examples/i3/mem-free.lua
Переменной mem_uev присваивается значение в самом начале и оно не обновляется, виджет показывает одно и то же значение.
Если первую строку (с присвоением значения mem_uev) перенести в функцию get_mem_seg, то всё начинает работать, виджет обновляется.

-mem_uev = assert(io.open('/proc/meminfo', 'r'))
-
 function get_mem_seg()
     local result = '[-?-]'
+    mem_uev = assert(io.open('/proc/meminfo', 'r'))
     mem_uev:seek('set', 0)
     for line in mem_uev:lines() do
         local key, value, um = string.match(line, '(.*): +(.*) +(.*)')

**Comment by shdown** [comment]
Thank you gor reporting, but I ask you to use English if possible, because otherwise non-Russian speakers will simply not understand what the issues you create are about.
