### ISSUE TITLE
barlib for lemonbar feature request

### ISSUE THREAD

**Issue by seamus-45** [shdown/luastatus#2]

**Comment by shdown** [comment]
As far as I can see, bspwm does not come with any kind of panel, and the `examples/panel/panel` script in the bspwm repository launches lemonbar. So I don’t know what exactly you are requesting. If you want a barlib for lemonbar, please rename the issue, or open a new one.

**Comment by seamus-45** [comment]
You are right, I'll rename the issue. 
As I understand, I also need a plugin for bspwm for full functionality? To obtain the status from bspw and etc..

**Comment by shdown** [comment]
>  As I understand, I also need a plugin for bspwm for full functionality? To obtain the status from bspw and etc..

It seems that the only way to monitor bspwm “status” is monitoring the output of `bspc subscribe report`. The `pipe` plugin, thus, would be sufficient.

**Comment by shdown** [comment]
OK, initial support added. Events are not supported yet, but hopefully will be at some point in the future.

**Comment by seamus-45** [comment]
Excellent work, thank you very much!
