### ISSUE TITLE
нумерация ревизий ebuild'ов (package revision)

### ISSUE THREAD

**Issue by itspec-ru** [shdown/luastatus#31]
Предлагаю немного упорядочить ebuild'ы для Gentoo

1. Для релизов ревизия (package revision) ebuild'а изначально не требуется.
То есть для релиза 0.3.0 имя файла ebuild'а должно было быть luastatus-0.3.0.ebuild,
релиз соответствует ревизии r0 и в имени файла отсутствует. В релизе 0.3.0 имя файла было сразу luastatus-0.3.0-r1.ebuild, что не совсем корректно, но допустимо.
Разумеется этот пункт имеет отношение только к последующим релизам, нет смысла менять старые.
Про переменные, используемые в ebuild'ах, в частности PR (package revision), можно посмотреть здесь https://devmanual.gentoo.org/ebuild-writing/variables/

2. Для "live ebuilds" (luastatus-9999) нумерацию ревизий наверное лучше вовсе убрать,
так как слишком часто добавляются новые фичи (barlibs, plugins). Либо при каждом изменении ebuild'а логично было бы увеличивать номер ревизии. Вообще говоря, "live ebuild" уже подрузамевает меняющиеся исходники в процессе разработки, и в portage большинство live ebuild'ов не имеют номеров ревизий.

3. При выпуске релиза нет смысла включать в него ebuild'ы старых релизов.
То есть в релизе 0.4.0 по идее должны быть только два ebuild'а
 luastatus-0.4.0.ebuild
 luastatus-9999.ebuild
Разумеется на момент выпуска релиза, в нашем случае, оба файла должны быть одинаковыми.

**Comment by shdown** [comment]
> Для "live ebuilds" (luastatus-9999) нумерацию ревизий наверное лучше вовсе убрать

А она была? Я её не вижу ни в имени файла, ни в нём самом.

Со всем остальным согласен; насколько я понимаю, всё, что нужно сделать сейчас — это удалить из master-ветки все non-live ебилды. Это и сделал.

**Comment by shdown** [comment]
И спасибо за поддержку ебилдов в актуальном состоянии.

**Comment by itspec-ru** [comment]
>И спасибо за поддержку ебилдов в актуальном состоянии.

Вам спасибо за Вашу работу!
