### ISSUE TITLE
'widget-examples/ move to examples/' updates

### ISSUE THREAD

**Issue by itspec-ru** [shdown/luastatus#35]
1. In README.md:
>You will find widget examples in \`contrib/widget-examples\`.

Probabli, must be
>You will find widget examples in the \`examples/\` directory.

2. In \`contrib/luastatus-9999.ebuild\` may also replace
>docompress -x /usr/share/doc/${PF}/widget-examples/${barlib}

with
>docompress -x /usr/share/doc/${PF}/examples/${barlib}

?

**Comment by itspec-ru** [comment]
Also in \`barlibs/i3/README.md\`
>Please see \`contrib/widget-examples/i3/README.md\` for the example of using this barlib.

must be 
>Please see \`examples/i3/README.md\` for the example of using this barlib.

**Comment by shdown** [comment]
Thanks!

> In `contrib/luastatus-9999.ebuild` may also replace
> `docompress -x /usr/share/doc/${PF}/widget-examples/${barlib}`
> with
> `docompress -x /usr/share/doc/${PF}/examples/${barlib}`
> ?

Well, probably yes, for consistency’s sake.
