### ISSUE TITLE
alsa-interactive-gauge.lua example: usability

### ISSUE THREAD

**Issue by itspec-ru** [shdown/luastatus#36]
При нажатии на "text block" раскрывается "gauge block",
при этом "text block" оказывается слева от "gauge block".

На мой взгляд это не очень удобно.
Чтобы повторно нажать на "text block" приходится передвигать мышь.
Визуально перескакивание "text block" выглядит так же не очень здорово (опять же, на мой взгляд).

Предлагаю при нажатии на "text block" его позицию не менять. "gauge block" раскрывается слева (так же как и было).

В коде достаточно изменить r[1] на r[2], r[2] на r[1] в 'cb', приерно так:

```
       local r = {}
        if gauge then
            local fg, bg = '#dcdcdc', '#444444'
            if t.mute then
                fg, bg = '#e03838', '#4a1414'
            end
            r[1] = {full_text=mk_gauge(level), color=fg, background=bg, instance='gauge'}
        end

        if t.mute then
            r[2] = {full_text='[mute]', color='#e03838'}
        else
            r[2] = {full_text=string.format('[%3d%%]', round(level * 100)), color='#718ba6'}
        end
        text_block_nchars = #r[2].full_text -- please note this does not work with Unicode.

```

**Comment by shdown** [comment]
Да, спасибо. Кстати, из текста виджета, по-моему, непонятно, что по gauge block можно кликать и громкость будет меняться. Нужно бы добавить комментарий.

**Comment by itspec-ru** [comment]
>Кстати, из текста виджета, по-моему, непонятно, что по gauge block можно кликать и громкость будет меняться.

Имя файла намекает на это.
