### ISSUE TITLE
Ошибка установки документации в gentoo linux

### ISSUE THREAD

**Issue by itspec-ru** [shdown/luastatus#37]
При использовании USE-флага "doc" получаем ошибку:
/var/tmp/portage/x11-misc/luastatus-9999/work/luastatus-9999/generate-man.sh: строка 8: rst2man: команда не найдена

В системе действительно нет команды "rst2man".
А пакет dev-python/docutils содержит команду "/usr/bin/rst2man.py".

P.S.
На всякий случай проверил на двух разных системах с gentoo linux: с архитектурами x86 и amd64. Результат тот же.

**Comment by shdown** [comment]
Странно, у меня работало.

**Comment by shdown** [comment]
ОК, я собирал старую версию.

Fixed with cbe50501fab46f6ec738a3a2c2aa229fb7cbefbb.

**Comment by itspec-ru** [comment]
which rst2man
which: no rst2man in (/sbin:/bin:/usr/sbin:/usr/bin)

locate тоже rst2man не находит

equery belongs /usr/bin/rst2man.py
 * Searching for /usr/bin/rst2man.py ... 
dev-lang/python-exec-2.4.6 (/usr/lib/python-exec/python-exec2)
dev-python/docutils-0.13.1 (/usr/bin/rst2man.py -> ../lib/python-exec/python-exec2)

Может быть дело в версии docutils

**Comment by itspec-ru** [comment]
Теперь действительно всё работает.
Спасибо!
