### ISSUE TITLE
[network-linux] signal_percent returns nil

### ISSUE THREAD

**Issue by teotwawki16** [shdown/luastatus#40]
The parameter signal_dbm works fine but signal_percent returns nil.

**Comment by shdown** [comment]
This is expected: some drivers only return signal in percents (presumably this is rare), some in dbms.

Same on my machine.

I guess this needs to be stated in network-linux/README.rst.

NetworkManager's formula of calculating percent from dbm is: 1 - 0.7 * (MAX_DBM - dbm) / (MAX_DBM - MIN_DBM), where dbm is clamped between MIN_DBM and MAX_DBM, MIN_DBM = -90, MAX_DBM = -20 (see examples/i3/wireless.lua, make_wifi_gauge function).
