### ISSUE TITLE
using a different fork of lemonbar

### ISSUE THREAD

**Issue by teotwawki16** [shdown/luastatus#43]
I found [this bar](https://github.com/krypt-n/bar) and it seems that they have a different implementation of fixing the multiline input problem your bar is having with the [official one](https://github.com/LemonBoy/bar).

I used [your fork](https://github.com/shdown/bar/tree/buffer-bug-fix) and it works. But I had issues with it because it doesn't support xft.

Is the bar I cited okay to use?

**Comment by shdown** [comment]
Considering input, it’s still broken, see https://github.com/LemonBoy/bar/issues/107#issuecomment-310899703.

I recommend unapplying https://github.com/krypt-n/bar/commit/00a3fe6f3485203896156480e86014136749a221 and applying my patch.

**Comment by teotwawki16** [comment]
Yes. I ended up using [this](https://github.com/drscream/lemonbar-xft) and applying your patch. And it works! Thanks!
