### ISSUE TITLE
multiple intances of luastatus running

### ISSUE THREAD

**Issue by ekomizer** [shdown/luastatus#46]
I tried reloading i3 for a couple of times. And upon checking htop, I now have multiple instances of luastatus running.

**Comment by shdown** [comment]
This is just threads.

You can see this by noting that:

* there are exactly `${your_number_of_widgets} + 1` of them;
* in `htop`, only one of them has white color, as opposed to green (meaning that it is a process, not a thread);
* in `htop`, after turning on “Hide userland process threads” in “Setup” → “Display options”, all of them but one disappear;
* `ps -C luastatus` only shows one process, while `ps -T -C luastatus` shows all of them (plus some weird thing named `threaded-ml`, I have no idea what it is).

**Comment by teotwawki16** [comment]
You're right. But I don't see `threaded-ml`.

**Comment by teotwawki16** [comment]
I did some investigation. Doing `ps -C luastatus` after a couple of refreshes really return multiple instances. But I figured a workaround and just placed this in my i3 config:
`status_command exec bash -c '[[ ! -z $(pgrep -x luastatus) ]] && pkill -x luastatus; luastatus-i3-wrapper -B no_separators ~/.config/luastatus/i3bar/*.lua || luastatus-i3-wrapper -B no_separators ~/.config/luastatus/i3bar/*.lua'`

**Comment by shdown** [comment]
What i3 version do you use?

**Comment by teotwawki16** [comment]
I'm using the latest stable release `i3-gaps-4.16.1-1`.

**Comment by teotwawki16** [comment]
My guess is that whenever I reload `i3`, the `status_command` executes again and, thus, running another `luastatus` process.

**Comment by shdown** [comment]
By “reload” you mean doing `i3-msg reload`, right?

I don’t know what the problem is yet, but what’s the point of this part of your script:
```luastatus-i3-wrapper -B no_separators ~/.config/luastatus/i3bar/*.lua || luastatus-i3-wrapper -B no_separators ~/.config/luastatus/i3bar/*.lua```
?

**Comment by teotwawki16** [comment]
In my i3 config, I combined reload and restart in one binding. I guess that's the culprit:
`bindsym $mod+F5 reload restart`

This was my `status_command` before replacing it:
`status_command exec luastatus-i3-wrapper -B no_separators ~/.config/luastatus/i3bar/*.lua`

**Comment by shdown** [comment]
What’s the reason of closing?
