### ISSUE TITLE
[request] display ethernet network's name

### ISSUE THREAD

**Issue by ekomizer** [shdown/luastatus#47]
Like a wifi's SSID.

**Comment by shdown** [comment]
My guess is that it’s specific to the tool you use to configure your ethernet connection. Which one do you use?

**Comment by ekomizer** [comment]
> Which one do you use?

I use `systemd-networkd`.

**Comment by ekomizer** [comment]
I misclicked.

**Comment by shdown** [comment]
OK, but what “name”, exactly, do you want to see? Is it the name of the `.network` file currently active? Is it the `Description=` field specified in it?

E.g. do you have a shell command that would output the desired “name”?

**Comment by ekomizer** [comment]
Looking at the `network-linux` plugin, what I'm trying to say is I'd like to have an ethernet option like the one from the `wifi` table which has an `ssid` entry. Currently, the `ethernet` table has only the `speed` entry. And the name that I'm referring to is the one configured from a network modem.

**Comment by shdown** [comment]
Can you provide a command that outputs the desired name?

**Comment by ekomizer** [comment]
I don't have any. I pressume that by only using the Linux kernel headers, you can take out the SSID of any WiFi network. I just thought if you could do the same for ethernet networks.

**Comment by shdown** [comment]
As far as I know, there’s no such thing as SSID/“network name” equivalent for Ethernet connection.

**Comment by ekomizer** [comment]
Yeah. I thought there is. Thanks anyway. Closing.
