### ISSUE TITLE
"network-rate" uses "binary prefix" divisor (1024) rather than "si prefix" divisor (1000)

### ISSUE THREAD

**Issue by jaimet** [shdown/luastatus#59]
Hi.

(This is more a question, rather than a bug, because I don't know whether your current implementation is "by design" or not.)

[network-rate.lua divides by 1024](https://github.com/shdown/luastatus/blob/e9d2c7ec395aac813b0ba5a518bf0603d4b4ed81/examples/dwm/network-rate.lua#L32), and so calculates the network rate in "kibibytes per second".

[Wikipedia's article on binary prefixes](https://en.wikipedia.org/wiki/Binary_prefix#Current_practice) says:

> Most computer hardware uses SI prefixes to state capacity and define other performance parameters such as **data rate**.

(emphasis mine!)

Is your "division by 1024" "by design", or should it be "division by 1000" in order to calculate the network rate in "kilobytes / second"?

**Comment by shdown** [comment]
> Is your "division by 1024" "by design", or should it be "division by 1000" in order to calculate the network rate in "kilobytes / second"?

After conducting some research, I would say that it should probably be “division by 1000”.
