### ISSUE TITLE
Error occurs when trying to use multiple widgets that use the mpd plugin

### ISSUE THREAD

**Issue by itspec-ru** [shdown/luastatus#63]
When trying to use multiple widgets using the mpd plugin, the error occurred "Error: status_command process exited unexpectedly (exit 0)"

Simple sample widget mpd-test.lua
`widget = {
    plugin = 'mpd',
    opts = {timeout = 2},
    cb = function(t) return {full_text = "test"} end
}
`

i3 config:
`status_command cd ~/.config/luastatus && exec luastatus-i3-wrapper -B no_separators mpd-test.lua`
Works properly

`status_command cd ~/.config/luastatus && exec luastatus-i3-wrapper -B no_separators mpd-test.lua mpd-test.lua`
Get error: "Error: status_command process exited unexpectedly (exit 0)"

This behavior started with version 0.5.0. Version 0.4.0 worked correctly.

**Comment by shdown** [comment]
Thanks for reporting this, please check if the version from the current master works.

**Comment by itspec-ru** [comment]
Now works perfect! Thanks!
